# Generated by Django 4.0.5 on 2022-06-29 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apithone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='identity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=90)),
                ('artist', models.CharField(max_length=90)),
                ('des', models.TextField()),
                ('uploded', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_songs', to='apithone.upload')),
            ],
        ),
    ]
