# Generated by Django 4.0.5 on 2022-07-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apithone', '0002_upload_identity_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='uploded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
