# Generated by Django 4.0.5 on 2022-07-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apithone', '0003_alter_song_uploded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='uploded',
        ),
    ]
