# Generated by Django 4.0.5 on 2022-06-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SONG_NAME', models.CharField(max_length=90)),
                ('SONG_BY', models.CharField(max_length=90)),
                ('SONG_DES', models.TextField()),
                ('SONG_IMG', models.ImageField(upload_to='pics')),
                ('SONG_UPLODED', models.DateTimeField(auto_now_add=True)),
                ('SONG_RATE', models.IntegerField()),
                ('FAVORITE', models.BooleanField()),
                ('SONG_CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='apithree.category')),
            ],
        ),
    ]
