# Generated by Django 4.0.5 on 2022-06-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apithree', '0004_alter_songs_song_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='SONG_IMG',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='songs',
            name='SONG_RATE',
            field=models.FloatField(),
        ),
    ]
